name: Update Galaga

on:
  workflow_dispatch:
  schedule:
    - cron: "17 0 * * *"
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Generate animation
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: nonameTAT
          games: galaga

      - name: Save animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
